//! Build-time migration discovery.
//!
//! Scans `sql/*.sql` at compile time, validates that the migrations form a
//! gapless sequence starting at `0`, and emits `$OUT_DIR/migrations_generated.rs`
//! holding an array of `EmbeddedMigration`s (the type comes from the shared
//! `kls-web-core` crate; see `src/migrations.rs`). Embedding via `include_str!`
//! keeps the single-binary deployment model — `sql/` need not ship next to the
//! binary. Adding a migration is just dropping a new numbered file into `sql/`.
//!
//! This mirrors klappstuhl_me's build.rs; the two apps share the runtime runner
//! (`kls_web_core::migrations`) but each embeds its own migration set.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo");
    let sql_dir = Path::new(&manifest_dir).join("sql");

    // Re-run if a file is added to or removed from the directory. `include_str!`
    // itself registers a per-file dependency, so editing an existing migration's
    // contents already triggers a recompile of the module that includes it.
    println!("cargo:rerun-if-changed={}", sql_dir.display());

    // Collect `<version> -> path`, keyed (and thus sorted) by the numeric version
    // parsed from the file stem. A BTreeMap also gives duplicate detection for free.
    let mut migrations: BTreeMap<u32, PathBuf> = BTreeMap::new();
    let entries = fs::read_dir(&sql_dir)
        .unwrap_or_else(|e| panic!("failed to read migrations directory {}: {e}", sql_dir.display()));

    for entry in entries {
        let path = entry.expect("failed to read directory entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("sql") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("migration file has a non-UTF-8 name: {}", path.display()));
        let version: u32 = stem.parse().unwrap_or_else(|_| {
            panic!(
                "migration file {} must be named <number>.sql (e.g. 1.sql), got stem {stem:?}",
                path.display()
            )
        });
        if let Some(existing) = migrations.insert(version, path.clone()) {
            panic!(
                "duplicate migration version {version}: {} and {}",
                existing.display(),
                path.display()
            );
        }
    }

    if migrations.is_empty() {
        panic!("no migrations found in {}", sql_dir.display());
    }

    // Enforce a gapless 0..N sequence. The runner relies on this: the "next
    // migration to apply" is always the one whose version equals `user_version`.
    for (index, version) in migrations.keys().enumerate() {
        if *version as usize != index {
            panic!(
                "migration sequence has a gap: expected {index}.sql but the next file is {version}.sql. \
                 Migrations must be numbered contiguously from 0."
            );
        }
    }

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit by hand.\n");
    generated.push_str(&format!(
        "pub const EMBEDDED_MIGRATIONS: [EmbeddedMigration; {}] = [\n",
        migrations.len()
    ));
    for (version, path) in &migrations {
        // `include_str!` accepts forward slashes on every platform; converting
        // avoids emitting backslash escapes into the literal on Windows.
        let literal = path.to_str().expect("migration path is valid UTF-8").replace('\\', "/");
        generated.push_str(&format!(
            "    EmbeddedMigration {{ version: {version}, sql: include_str!(\"{literal}\") }},\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is always set by cargo");
    let dest = Path::new(&out_dir).join("migrations_generated.rs");
    fs::write(&dest, generated).expect("failed to write generated migrations file");
}
