//! Vantage's own `admin.db` migration set, wired to the shared runner.
//!
//! The generic engine that applies and integrity-checks a migration set lives in
//! the shared `kls-web-core` crate (`kls_web_core::migrations::run`); this module
//! only supplies the build-time-embedded set and the `migrate` entry point handed
//! to the connection pool's `with_init`. Adding a migration is just dropping a new
//! numbered file into `sql/` (see `build.rs`) — that is how each admin feature
//! slice brings its own tables when it moves in (ADMIN_SEPARATION_PLAN Phase 4).

pub use kls_web_core::migrations::*;

// Pulls in `pub const EMBEDDED_MIGRATIONS: [EmbeddedMigration; N]` generated by
// build.rs. The array literal is type-checked against the `EmbeddedMigration`
// struct re-exported above from the shared crate.
include!(concat!(env!("OUT_DIR"), "/migrations_generated.rs"));

/// Name of the table tracking applied migrations and their checksums.
const TRACKING_TABLE: &str = "schema_migrations";

/// Runs all pending `admin.db` migrations and verifies applied ones. Handed to
/// the connection pool's `with_init`, so every pooled connection runs it; the
/// runner serialises on the write lock and no-ops once the schema is current.
pub fn migrate(conn: &mut rusqlite::Connection) -> anyhow::Result<()> {
    run(conn, &EMBEDDED_MIGRATIONS, TRACKING_TABLE)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[allow(clippy::const_is_empty)] // guard against the const set ever being emptied
    fn embedded_migrations_are_contiguous() {
        for (index, migration) in EMBEDDED_MIGRATIONS.iter().enumerate() {
            assert_eq!(migration.version as usize, index, "migration {index} out of sequence");
        }
        assert!(!EMBEDDED_MIGRATIONS.is_empty(), "expected at least one migration");
    }

    #[test]
    fn migrate_fresh_database_applies_schema() {
        let mut conn = rusqlite::Connection::open_in_memory().expect("open in-memory db");
        conn.busy_timeout(std::time::Duration::from_secs(5)).unwrap();
        migrate(&mut conn).expect("migrate fresh db");

        // The account/session foundation exists after migrating.
        for table in ["account", "session", "storage"] {
            let n: u32 = conn
                .query_row(
                    "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?",
                    [table],
                    |r| r.get(0),
                )
                .unwrap();
            assert_eq!(n, 1, "table {table} missing after migrate");
        }
    }
}
